name: build

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch: 

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: pull source
        uses: actions/checkout@v4
        with:
          repository: Chzxxuanzheng/Stapxs-QQ-Lite-X
          ref: test 
          submodules: recursive
          fetch-depth: 0
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: configure pnpm
        uses: pnpm/action-setup@v4

      - name: enable Corepack and prepare pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm -v

      - name: install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: build vue app
        run: pnpm build

      - name: configure docker buildx
        uses: docker/setup-buildx-action@v3

      - name: login registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push container image
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: |
            ghcr.io/axycri7/stapxs-qq-lite-x-docker:latest
            ghcr.io/axycri7/stapxs-qq-lite-x-docker:${{ github.sha }}-${{ github.run_id }}
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: logout registry
        if: always()
        run: docker logout ghcr.io